### ISSUE TITLE
[Bug] When keep hold hotkey, will sleep 0.5 second

### ISSUE THREAD

**Issue by zw963** [kawao/x-set-keys#3]
e.g. in terminal:

I press `C-f`, it foward a char, and press `C-f` again, forward a char again.

And then, I keep hold `C-f`, will sleep 0.5 second, add then move char forward quickly.

if not start x-set-key,  keep hold `C-f`, will move char forward quickly imediately.

Thank

**Comment by zw963** [comment]
Even, i exclude my emacs in x-set-keys, but this strange behavior still effect emacs.

**Comment by kawao** [comment]
Usually keyboard repeat delay is controlled by X Window System, and the xset command line tool (or probably GUI tool of your display environment) can be used to show and change keyboard repeat delay.

But currently in x-set-keys keyboard repeat delay is hard-coded in source.
And I changed keyboard repeat delay of x-set-keys from 1 second to 0.5 second  in new revision.

Thank you.

**Comment by zw963** [comment]
Hi, I retry it after recompile it, it better now, Thanks you very much.

**Comment by zw963** [comment]
Hi, I try it all day today, even change code to following, and recompile:

```c
#define _500MS 100000ul
#define _is_after_repeat_delay(t1, t2)                                  \
  ((t2).tv_sec == (t1).tv_sec)                                          \
  ? (t2).tv_usec > (t1).tv_usec + _500MS                                \
  : (((t2).tv_sec == (t1).tv_sec + 1)                                   \
     ? (t2).tv_usec + _500MS > (t1).tv_usec                             \
     : (t2).tv_sec > (t1).tv_sec)
```

But the incorrect behavior same as before i think, 
But this just change another unexpect behavior ... not what i want.

Following is a more accurate describe for my issue:

1. Following is a test line in my terminal
 my cursor is after `a`

this is aI test line in terminal 

2. what i want is to move to next a(in terminal) quickly.

3. next step, I start with keep press `C-F`,  not key up.

4. after i press `C-F`,  no key up, the cursor is not move in 0.5 second

5. After 0.5 second, cursor is start to move very very quickly, as i set it to `100000ul`.

What i expect is:

after i first press `C-F`,  no key up, cursor is move immediately. (this behavior is default if not run x-set-keys)

Current Behavior:
after i first press `C-F`,  no key up,  still need wait 0.5 second, and then move very very quickly.
(this very very quickly moving after 0.5 second is not my intention)

Thanks

**Comment by kawao** [comment]
Thanks for reporting this issue.
I think I fixed it.
Please try the new source code and see if it works for you.

**Comment by zw963** [comment]
Sorry for late reply, It seem like better. i will use a some period and report here if have any trouble. 

Thanks.

**Comment by zw963** [comment]
Seem like this issue still exists, the 0.5-1.0 seconds delay still happen for me.

Thanks.

**Comment by kawao** [comment]
I modified the program to obtain delay and interval of autorepeat of keyboard from system.
So in new source code, you can change these values using the keyboard settings program of your system.

Hopes this works for you.

**Comment by zw963** [comment]
Thanks, i wil try this later.

**Comment by zw963** [comment]
Hi, I try to compile with new code, and will report here if it worked.

**Comment by zw963** [comment]
I think x-set-keys exist some special code, which make x-set-keys controlled keyboard device normal behavior work different with normal keyboard. (Not my X system problem, maybe we should revert some code, sorry)

I think I am not describe clearly what the problem, Following is a more friendly explain about my editing working process:

Following example suppose i use `Ctrl+b` forward a char in some application.

1.  general, i move character one by one,  Keeping press Ctrl, not release, and Press `b`, `up`, `b`, `up`,
it worked fine with `x-set-keys`.

2.  But for some case, i want quickly move forward, What i do is, change above to:  Keeping press Ctrl not release, and Keep press `b` not release too, in this case, move speed is quickly, it worked too for `x-set-keys`

3.  But, when i switch from `keeping press Ctrl, press b, up, b, up ...` to `keeping press Ctrl,  keeping press b`,  if without x-set-keys, this switch almost immediately, after enable x-set-keys,  this switch 
need spent 0.3-0.5 seconds delay before the cursor quickly move as usual.

Does i describe clearly this time? please like me know, thanks

**Comment by kawao** [comment]
What if you run the following on a terminal?

```sh
$ xset r rate 200 20
```

Thanks.

**Comment by zw963** [comment]
@kawao , 

>> xset r rate 200 20

This is worked for me, it worked as expect again after run this!

but, when run x-set-keys again, this strange behavior back!

**Comment by kawao** [comment]
Thank you for reporting.

Please adjust repeat delay and repeat speed of the keyboard using the setting tool of your desktop environment.

If you are using Deepin: <https://wiki.deepin.org/index.php?title=Deepin_Desktop_Environment#Set_Keyboard_Properties>

If you are using GNOME: <https://help.gnome.org/users/gnome-help/stable/keyboard-repeat-keys.html.en>

**Comment by zw963** [comment]
What you means is，after rerun x-set-key，i always need use system keyboard tools to restore config?

**Comment by kawao** [comment]
> What you means is，after rerun x-set-key，i always need use system keyboard tools to restore config?

No, only once.
When x-set-keys starts up, the desktop environment will reset these settings with its own settings.
So the setting by the xset command will be overwritten by the setting of the desktop environment.
So you need to set these values using tools of the desktop environment.

Thanks.

**Comment by zw963** [comment]
@kawao , hi, sorry for say: it not work.

after rerun x-set-keys, i have to adjust keyboard config again to eliminate delay bug.
i think adjust Deepin keyboard config should same as run `xset r rate 200 20` directly in my
terminal.

But, when i rerun x-set-keys, it broken xset config again, so, i think this issue is caused by
x-set-keys,  frequently.

BTW: when i use other library, e.g. rbindkeys, it not cause this delay issue.

Thanks

**Comment by kawao** [comment]
I see. Thank you for taking your time.

Please edit your startup script to execute `xset r rate 200 20` after launching x-set-keys.
At present I suppose it will have only to.

**Comment by zw963** [comment]
@kawao , I done it, but, don't know why, append line `xset r rate 200 20` after `x-set-keys` command  not work for me. as following example

/usr/local/bin/x-set-keys_wrapper
```sh
#!/bin/sh

x-set-keys "$@"
x-set r rate 200 20
```

When run /usr/local/x-set-key_wrapper, it not worked.

So, i have to add a function into .bashrc.

$HOME/.bashrc

```sh

function x-set-keys1 () {
  /usr/local/bin/x-set-keys
  x-set r rate 200 20
}
x-set-keys1
```

it worked now.

Thanks

**Comment by zw963** [comment]
Sorry, it still not work.  `x-set r rate 200 20` maybe run before `x-set-keys` is finished.

**Comment by zw963** [comment]
I try like this too, it still not work.


```sh
$ROOT/bin.real/$basename ${keyboard+-d} $keyboard \
          -e 'Emacs' \
          -e 'Konsole' \
          -e 'konsole' \
          -e 'Deepin-terminal' \
          $ROOT/emacslike.conf &

FAIL=0

for job in `jobs -p`; do
    echo $job
    wait $job || let "FAIL+=1"
done

if [ "$FAIL" == "0" ]; then
    echo "YAY!"
else
    echo "FAIL! ($FAIL)"
fi
```

seem like `wait $job` is blocked.

**Comment by zw963** [comment]
the final work solution is:

$HOME/.bashrc

```sh
function x-set-keys1 () {
    daemon x-set-keys
    sleep 1
    xmodmap ~/.Xmodmap &>/dev/null
    xset r rate 200 20
}

x-set-keys1
```

**Comment by zw963** [comment]
current, i have to write a daemon use bash shell, it do following things every 10 seconds:

1.  if `Xmodmap` is broken by x-set-keys, rerun `xmodmap ~/.Xmodmap`
2. if xset repeat delay is broken by x-set-keys, rerun `xset r rate 360 20`
3. if a usb keyboard is attached, reboot `x-set-keys` use that device.

for now, it worked.

**Comment by zw963** [comment]
i have issue for `1`, `2`,  individually, i think maybe could fix from x-set-keys.

`3`,  i don't think this is a issue.

Thanks

**Comment by zw963** [comment]
Hi, I am very happy to say, this issue is fixed!  for 01233fe
